#
# This file contains course and lab specific parameters for drivers.
# It was generated by genhdrs.pl. Do not modify it.
#
package Driverhdrs;

$LAB = "lab3";
$SERVER_NAME = "autolab.cs.cmu.edu";
$SERVER_PORT = "80";
$COURSE_NAME = "15411-f09";
$AUTOGRADE_TIMEOUT = "240";
1;
