
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 08 00:07:22 HKT 2015
//----------------------------------------------------

package edu.cmu.cs.l1.parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int MOD = 14;
  public static final int NEG = 15;
  public static final int PLUS = 9;
  public static final int RBRACE = 5;
  public static final int RPAREN = 7;
  public static final int INT = 3;
  public static final int DIVIDEASSIGN = 19;
  public static final int RETURN = 21;
  public static final int LPAREN = 6;
  public static final int LBRACE = 4;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int TIMESASSIGN = 18;
  public static final int DIVIDE = 12;
  public static final int SEMICOL = 8;
  public static final int PLUSASSIGN = 16;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int ASSIGN = 13;
  public static final int MINUSASSIGN = 17;
  public static final int MODASSIGN = 20;
}

